### ISSUE TITLE
memberof reference to exports not found

### ISSUE THREAD

**Issue by knownasilya** [documentationjs/dev-documentation#5]
I get the following error:

> lib/token.js:4: memberof reference to exports not found

When I run this in the following project file: https://github.com/knownasilya/just-auth/blob/master/lib/token.js#L5

I run `dev-documentation` in the top level directory.

**Comment by tmcw** [comment]
This is an issue upstream in documentation: https://github.com/documentationjs/documentation/issues/113

**Comment by knownasilya** [comment]
Ah, thanks for pointing it out.
